// KEYWORDS
const String RIGHT = "right";
const String LEFT = "left";
const String UP = "up";
const String DOWN = "down";

// STATE
const String BEFORE_START = "BEFORE_START";
const String BEFORE_DRAWING_MAIN_BRANCH = "BEFORE_DRAWING_MAIN_BRANCH";
const String DRAWING_FIRST_WAVE = "DRAWING_FIRST_WAVE";
const String DRAWING_SECOND_WAVE = "DRAWING_SECOND_WAVE";
const String CALCULATE_LEAFS_SETTINGS = "CALCULATE_LEAFS_SETTINGS";
const String MOVING_TO_NEXT_LEAF_CREATION_SPOT = "MOVING_TO_NEXT_LEAF_CREATION_SPOT";
const String DRAWING_LEAF_PART_A = "DRAWING_LEAF_PART_A";
const String DRAWING_LEAF_PART_B = "DRAWING_LEAF_PART_B";
const String FINISH = "FINISH";

// SERVO
const int MAIN_BRANCH_LOCATION = 92;

// ENCODER
const long NO_MANS_LAND = 150;
const long EDGE_LEAF_NO_MANS_LAND = 800;
const int MIN_ENCODER_SEEED = 60;
const int MAX_ENCODER_SEEED = 80;

// LEAFS
const int MIN_LEAFS = 2;
const int MAX_LEAFS = 5;
const int MIN_SERVO_SEEED_SLOW = 2;
const int MAX_SERVO_SEEED_SLOW = 2;
const int MIN_SERVO_SEEED = 4;
const int MAX_SERVO_SEEED = 4;
const int MIN_SERVO_DESTINATION_UP = 95;
const int MAX_SERVO_DESTINATION_UP = 97;
const int MIN_SERVO_DESTINATION_DOWN = 87;
const int MAX_SERVO_DESTINATION_DOWN = 89;

// Servo Movements
//
// FIRST WAVE DATA
//
// destinations perimeter
const int FIRST_WAVE_FROM_MIN_SERVO_DESTINATION = 87;
const int FIRST_WAVE_FROM_MAX_SERVO_DESTINATION = 91;
const int FIRST_WAVE_TO_MIN_SERVO_DESTINATION = 93;
const int FIRST_WAVE_TO_MAX_SERVO_DESTINATION = 97;
// speeds perimeter
const int FIRST_WAVE_MIN_SERVO_SPEED = 2;
const int FIRST_WAVE_MAX_SERVO_SPEED = 4;
//
// SECOND WAVE DATA
//
// destinations perimeter
//  wave above main branch
const int SECOND_WAVE_FROM_MIN_SERVO_DESTINATION_UP = 92;
const int SECOND_WAVE_FROM_MAX_SERVO_DESTINATION_UP = 94;
const int SECOND_WAVE_TO_MIN_SERVO_DESTINATION_UP = 95;
const int SECOND_WAVE_TO_MAX_SERVO_DESTINATION_UP = 99;
//  wave below main branch
const int SECOND_WAVE_FROM_MIN_SERVO_DESTINATION_DOWN = 85;
const int SECOND_WAVE_FROM_MAX_SERVO_DESTINATION_DOWN = 89;
const int SECOND_WAVE_TO_MIN_SERVO_DESTINATION_DOWN = 90;
const int SECOND_WAVE_TO_MAX_SERVO_DESTINATION_DOWN = 92;
// speed
const int SECOND_WAVE_MIN_SERVO_SPEED = 2;
const int SECOND_WAVE_MAX_SERVO_SPEED = 8;

// GENERAL
const int DEFAULT_SPEED = 90;